config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/SQAaaS:
      branch: master
      repo: https://github.com/EOSC-synergy/SQAaaS
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/SQAaaS git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-burgundy-chameleon.sh
        container: qc.acc_skimpy-amaranth-bombay
  QC.Doc:
    repos:
      github.com/EOSC-synergy/SQAaaS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-azure-millipede.sh
        container: qc.doc_dorky-gamboge-wombat
      github.com/EOSC-synergy/SQAaaS git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-saffron-foxhound.sh
        container: qc.doc_jumpy-cardinal-impala
      github.com/EOSC-synergy/SQAaaS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-auburn-coral.sh
        container: qc.doc_scummy-salmon-tuatara
  QC.Lic:
    repos:
      github.com/EOSC-synergy/SQAaaS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-harlequin-serval.sh
        container: qc.lic_gamy-vermilion-loon
  QC.Sty:
    repos:
      github.com/EOSC-synergy/SQAaaS hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-tomato-husky.sh
        container: qc.sty_surly-peach-axolotl
  QC.Ver:
    repos:
      github.com/EOSC-synergy/SQAaaS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-crimson-macaw.sh
        container: qc.ver_zippy-chocolate-guppy
timeout: 5400
