config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-olivine-vulture.sh
        container: qc.acc_cloudy-cinnabar-penguin
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-charcoal-olm.sh
        container: qc.doc_muggy-cobalt-wolverine
      github.com/EOSC-synergy/sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-sapphire-dragon.sh
        container: qc.doc_silly-carmine-chihuahua
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-celadon-mole.sh
        container: qc.lic_chummy-tomato-buzzard
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-denim-quokka.sh
        container: qc.ver_skinny-flax-monkey
timeout: 5400
