config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/sqaaas:
      branch: main
      repo: https://github.com/orviz/yprov-sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Uni:
    repos:
      github.com/HPCI-Lab/sqaaas commands:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-peach-cow.sh
        container: qc.uni_droopy-rose-sparrow
timeout: 5400
