config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/sqaaas:
      branch: main
      repo: https://github.com/HPCI-Lab/sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-ruby-angora.sh
        container: qc.acc_thirsty-orange-akbash
  QC.Doc:
    repos:
      github.com/HPCI-Lab/sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-corn-bulldog.sh
        container: qc.doc_boozy-platinum-lion
      github.com/HPCI-Lab/sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-scarlet-malamute.sh
        container: qc.doc_cranky-cardinal-paradise
      github.com/HPCI-Lab/sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-periwinkle-fox.sh
        container: qc.doc_gimpy-gamboge-bonobo
      github.com/HPCI-Lab/sqaaas restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-cardinal-mule.sh
        container: qc.doc_hilly-ruby-chihuahua
  QC.Lic:
    repos:
      github.com/HPCI-Lab/sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-flax-earwig.sh
        container: qc.lic_gloppy-fuchsia-tuatara
  QC.Sec:
    repos:
      github.com/HPCI-Lab/sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-red-civet.sh
        container: qc.sec_greasy-ivory-lobster
  QC.Sty:
    repos:
      github.com/HPCI-Lab/sqaaas flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-asparagus-hornet.sh
        container: qc.sty_gamy-bronze-cat
      github.com/HPCI-Lab/sqaaas hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-salmon-dragonfly.sh
        container: qc.sty_grumpy-wisteria-warthog
      github.com/HPCI-Lab/sqaaas jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-goldenrod-chin.sh
        container: qc.sty_jumpy-turquoise-otter
      github.com/HPCI-Lab/sqaaas oclint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-ultramarine-badger.sh
        container: qc.sty_thirsty-orchid-cockroach
  QC.Uni:
    repos:
      github.com/HPCI-Lab/sqaaas commands:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-brass-yak.sh
        container: qc.uni_cozy-viridian-squirrel
  QC.Ver:
    repos:
      github.com/HPCI-Lab/sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-sepia-macaw.sh
        container: qc.ver_trippy-yellow-echidna
timeout: 5400
