config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/sqaaas:
      branch: main
      repo: https://github.com/HPCI-Lab/sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-turquoise-opossum.sh
        container: qc.acc_breezy-purple-owl
  QC.Doc:
    repos:
      github.com/HPCI-Lab/sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-cyan-foxhound.sh
        container: qc.doc_woolly-plum-budgerigar
      github.com/HPCI-Lab/sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-magnolia-indri.sh
        container: qc.doc_wimpy-periwinkle-mau
      github.com/HPCI-Lab/sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-vermilion-spoonbill.sh
        container: qc.doc_baggy-bistre-lion
      github.com/HPCI-Lab/sqaaas restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-gold-camel.sh
        container: qc.doc_greasy-auburn-urchin
  QC.Lic:
    repos:
      github.com/HPCI-Lab/sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-tan-beagle.sh
        container: qc.lic_cloudy-khaki-horse
  QC.Sec:
    repos:
      github.com/HPCI-Lab/sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-ruby-barb.sh
        container: qc.sec_ugly-magenta-wildebeest
  QC.Sty:
    repos:
      github.com/HPCI-Lab/sqaaas flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-brown-chin.sh
        container: qc.sty_lousy-pink-coral
      github.com/HPCI-Lab/sqaaas hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-auburn-uguisu.sh
        container: qc.sty_shaggy-thistle-coati
      github.com/HPCI-Lab/sqaaas jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-heliotrope-akita.sh
        container: qc.sty_lumpy-khaki-rat
  QC.Uni:
    repos:
      github.com/HPCI-Lab/sqaaas pytest:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-champagne-baboon.sh
        container: qc.uni_sunny-burgundy-badger
  QC.Ver:
    repos:
      github.com/HPCI-Lab/sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-copper-chihuahua.sh
        container: qc.ver_cranky-charcoal-paradise
timeout: 5400
