config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-sepia-cat.sh
        container: qc.acc_beady-celadon-gerbil
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-sepia-urchin.sh
        container: qc.doc_sunny-persimmon-snake
      github.com/EOSC-synergy/sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-linen-heron.sh
        container: qc.doc_cranky-thistle-mongoose
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-lilac-chicken.sh
        container: qc.lic_muggy-green-stingray
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-pumpkin-avocet.sh
        container: qc.ver_slaphappy-mauve-hyrax
timeout: 5400
