services:
  qc.uni_droopy-rose-sparrow:
    image: eoscsynergy/sqaaas-pytest:7.1.3-alpha
    command: >
      sh -c "pip install requests
      && sleep 6000000"
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  web:
    container_name: web
    build:
      context: ./github.com/HPCI-Lab/sqaaas
      dockerfile: Dockerfile.1
    restart: on-failure
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      USER: neo4j
      PASSWORD: password
      ADDRESS: db:7687
    volumes:
      - yprov_data:/app/conf
  db:
    container_name: db
    image: "neo4j:enterprise"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: eval
      NEO4J_PLUGINS: '["graph-data-science"]'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
        test: ["CMD", "curl", "-f", "http://db:7474"]
        interval: 30s
        timeout: 10s
        retries: 5
volumes:
  neo4j_data:
  neo4j_logs:
  yprov_data:
version: '3.7'
